# Generated by Django 5.1.4 on 2025-01-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('entries', models.IntegerField(default=0, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
